version: '3.7'

services:
  web:
    build: projectGoguma
    command: python manage.py runserver 0.0.0.0:8000 --settings=projectGoguma.settings.dev
    volumes:
      - ./projectGoguma/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev

    depends_on:
      - db
  db:
    image: postgres:13.5-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db

volumes:
    postgres_data: